name: Initialize Project

on:
  workflow_dispatch:

permissions: write-all
env:
  token = ${{secrets.GH_TOKEN}}
jobs:
  InitTerraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
      - name: init terraform
        run: |
          terraform init
      - name: terraform plan
        run: | 
          terraform plan -no-color 
          