name: Initialize Project

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.GH_TOKEN }}

permissions: write-all

jobs:
  InitTerraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
      - name: init terraform
        run: |
          terraform init
      - name: terraform plan
        run: | 
          terraform plan -var="gh_token=$TOKEN"-no-color 
          